Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Shared folder for token
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.define("aelasriS") do |aelasriS|
    aelasriS.vm.hostname = "aelasriS"
    aelasriS.vm.network "private_network", ip: "192.168.56.110"
    aelasriS.vm.provision "shell", path: "./k3s_controller.sh"

    aelasriS.vm.provider "virtualbox" do |vb|
      vb.name = "aelasriS"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define("aelasriSW") do |aelasriSW|
    aelasriSW.vm.hostname = "aelasriSW"
    aelasriSW.vm.network "private_network", ip: "192.168.56.111"
    aelasriSW.vm.provision "shell", inline: <<-SHELL
      set -e

      sudo apt-get update -y
      sudo apt-get install -y curl

      while [ ! -f /vagrant/node-token ]; do
        echo "Waiting for the token file..."
        sleep 5
      done

      K3S_TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="$K3S_TOKEN" sh -

      echo "k3s agent setup complete."
    SHELL

    aelasriSW.vm.provider "virtualbox" do |vb|
      vb.name = "aelasriSW"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end


# Vagrant.configure("2") do |config|
#   config.vm.box = "debian/bullseye64"

#   config.vm.define("aelasriS") do |aelasriS|
#     aelasriS.vm.hostname = "aelasriS"
#     aelasriS.vm.network "private_network", ip: "192.168.56.110"
#     aelasriS.vm.provision "shell", path: "./k3s_controller.sh"

#     aelasriS.vm.provider "virtualbox" do |vb|
#       vb.gui = true
#       vb.memory = "4096"
#     end
#   end

#   config.vm.define("aelasriSW") do |aelasriSW|
#     aelasriSW.vm.hostname = "aelasriSW"
#     aelasriSW.vm.network "private_network", ip: "192.168.56.111"
#     aelasriSW.vm.provision "shell", path: "./k3s_agent.sh"

#     aelasriSW.vm.provider "virtualbox" do |vb|
#       vb.gui = true
#       vb.memory = "4096"
#     end
#   end
# end