Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define("z3lnS") do |z3lnS|
    z3lnS.vm.hostname = "z3lnS"
    z3lnS.vm.network "private_network", ip: "192.168.56.110"
    z3lnS.vm.provision "shell", path: "./k3s-master.sh"

    z3lnS.vm.provider "virtualbox" do |vb|
      vb.name = "z3lnS"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define("z3lnSW") do |z3lnSW|
    z3lnSW.vm.hostname = "z3lnSW"
    z3lnSW.vm.network "private_network", ip: "192.168.56.111"
    z3lnSW.vm.provision "shell", path: "./k3s-worker.sh"

    z3lnSW.vm.provider "virtualbox" do |vb|
      vb.name = "z3lnSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
